import jsPDF from 'jspdf'
import type { ContentBrief } from '../components/ContentBriefGenerator'

export function exportBriefToPDF(brief: ContentBrief) {
  const doc = new jsPDF()

  // Set up fonts and colors
  const primaryColor: [number, number, number] = [79, 70, 229] // Indigo
  const secondaryColor: [number, number, number] = [107, 114, 128] // Gray

  // Header
  doc.setFontSize(24)
  doc.setTextColor(...primaryColor)
  doc.text('Content Brief Generator', 20, 30)

  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text(brief.title, 20, 50)

  // Description
  doc.setFontSize(12)
  doc.setTextColor(...secondaryColor)
  const descriptionLines = doc.splitTextToSize(brief.description, 170)
  doc.text(descriptionLines, 20, 70)

  let yPosition = 90

  // Keywords section
  doc.setFontSize(14)
  doc.setTextColor(...primaryColor)
  doc.text('Target Keywords:', 20, yPosition)
  yPosition += 10

  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  brief.keywords.forEach((keyword, index) => {
    doc.text(`• ${keyword}`, 25, yPosition + (index * 8))
  })
  yPosition += brief.keywords.length * 8 + 15

  // Content Structure
  if (yPosition > 250) {
    doc.addPage()
    yPosition = 30
  }

  doc.setFontSize(14)
  doc.setTextColor(...primaryColor)
  doc.text('Content Structure:', 20, yPosition)
  yPosition += 10

  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)

  brief.outline.forEach((section, index) => {
    if (yPosition > 260) {
      doc.addPage()
      yPosition = 30
    }

    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text(`${index + 1}. ${section.section}`, 20, yPosition)
    doc.setFontSize(8)
    doc.setTextColor(...secondaryColor)
    doc.text(`(${section.wordCount} words)`, 170, yPosition)
    yPosition += 8

    doc.setFontSize(10)
    const descriptionLines = doc.splitTextToSize(section.description, 160)
    doc.text(descriptionLines, 25, yPosition)
    yPosition += descriptionLines.length * 6 + 8
  })

  // SEO Recommendations
  if (yPosition > 200) {
    doc.addPage()
    yPosition = 30
  }

  doc.setFontSize(14)
  doc.setTextColor(...primaryColor)
  doc.text('SEO Recommendations:', 20, yPosition)
  yPosition += 10

  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  doc.text('Title Tag:', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  const titleLines = doc.splitTextToSize(brief.seoRecommendations.titleTag, 160)
  doc.text(titleLines, 25, yPosition)
  yPosition += titleLines.length * 6 + 10

  doc.setFontSize(12)
  doc.text('Meta Description:', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  const metaLines = doc.splitTextToSize(brief.seoRecommendations.metaDescription, 160)
  doc.text(metaLines, 25, yPosition)
  yPosition += metaLines.length * 6 + 10

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(...secondaryColor)
    doc.text(`Generated by Content Brief Generator - Page ${i} of ${pageCount}`, 20, 285)
    doc.text(new Date().toLocaleDateString(), 150, 285)
  }

  // Save the PDF
  const fileName = `${brief.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_brief.pdf`
  doc.save(fileName)
}
